# Generated by Django 3.1.5 on 2021-01-27 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='hint',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='answer',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='option1',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='option2',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='option3',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='option4',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
